# PDL_two_layer_script15.py
# ============================================================
# Two layers: entity states and relation states.
# Is the disagreement a gauge, or a genuine object?
#
# ############################################################
# TERMINOLOGY (corpus rule, non-negotiable)
#   Valence cores are K_24 and K_28: complete graphs on ENTITIES.
#   The literal K_4 of D61 denotes the electron closure only.
#   Composite nucleon closures (K_nuc) are not treated here.
#   Small complete graphs below are abstract test structures, not
#   electron closures.
# ############################################################
#
# WHERE THIS COMES FROM
#   Everything computed in this session has lived on ONE layer: the
#   entity states x_i = +-1, with relations entering only as the
#   induced product sigma_ij = x_i x_j. That was deliberate --- D68
#   showed the axioms are blind to the phase, which lives on the
#   entities. But it also means relations were never treated as
#   objects in their own right.
#
#   D42 does treat them as objects: the proton relations p_k appear
#   as VERTICES of cross-triangles. A relation at one level is an
#   entity at the next. The corpus therefore already performs the
#   level shift, without naming it.
#
# THE CONSTRUCTION
#   Give each edge its own state y_ij, independent of the entities,
#   and define the DISAGREEMENT
#        delta_ij = y_ij * sigma_ij,   sigma_ij = x_i x_j.
#   delta = +1: the relation agrees with its endpoints; -1: it does
#   not. delta is invariant under the global inversion x -> -x (both
#   sigma and y are), so it is legitimate on relational data. It is
#   NOT switching-invariant, so it sees what C4 cannot. And it is
#   defined by a comparison, not by a minimisation --- the first
#   object of this session whose definition does not close on an
#   extremum.
#
# THE DANGER, and why this script exists
#   If delta always factorises as delta_ij = z_i z_j for some vertex
#   assignment z, then setting x'_i = x_i z_i makes the disagreement
#   vanish identically: it is a pure GAUGE, carrying no information,
#   and the two-layer picture collapses back to the one-layer one.
#   That is the same obstacle every construction hit this session,
#   and it is the FIRST thing tested below.
#
#   Whether delta can factorise is a question about cycles, not
#   about size: delta factorises iff its product around every cycle
#   is +1 (Harary). On a COMPLETE graph all cycles are generated by
#   triangles, so constraining triangles constrains everything and
#   delta is very likely a gauge. On a SPARSE mesh there are long
#   cycles no triangle controls, and delta may survive. The sea is
#   sparse. Both regimes are therefore tested, and a negative result
#   on complete graphs alone would NOT close the question.
#
# THE THREE QUESTIONS
#   Q1  Which layer does C2 constrain --- the induced signs sigma,
#       or the proper signs y? Under each reading, what is the space
#       of admissible delta?
#   Q2  Is delta always of the form z_i z_j (a gauge), or can it be
#       cohomologically non-trivial? Measured as: the number of
#       admissible delta, versus the 2^(n-1) that are gauges.
#   Q3  If delta survives, do two DESYNCHRONISED pulsations (one per
#       layer) leave it without a fixed point? A beat has no fixed
#       point; a common minimum does. This is where a motor would
#       have to come from.
#
# PREDICTION, recorded before running
#   On complete graphs delta is expected to be a pure gauge under
#   the reading "C2 constrains y", because triangles generate the
#   cycle space. On sparse meshes with independent cycles, the
#   number of admissible delta should exceed the number of gauges
#   by exactly a factor 2^c with c = m - n + 1 the cyclomatic
#   number, IF C2 constrains only sigma. Any departure from this is
#   the result.
#
# Exact integer arithmetic. Standard library only.
#
# Author: Cedric Laubscher
# Date:   August 2026
# ============================================================

import itertools
from itertools import combinations

print("=" * 74)
print("PDL_two_layer_script15.py -- entity layer vs relation layer")
print("=" * 74)
print()


# ============================================================
# Machinery
# ============================================================

def induced(x, edges):
    return tuple(x[u] * x[v] for (u, v) in edges)


def triangles_of(n, edges):
    E = {frozenset(e) for e in edges}
    return [T for T in combinations(range(n), 3)
            if all(frozenset(p) in E for p in combinations(T, 2))]


def eidx_map(edges):
    return {frozenset(e): k for k, e in enumerate(edges)}


def tri_ok(sig, T, em):
    a, b, c = T
    return (sig[em[frozenset((a, b))]] *
            sig[em[frozenset((a, c))]] *
            sig[em[frozenset((b, c))]]) == 1


def cycle_basis(n, edges):
    """Fundamental cycles as edge-index sets, via a spanning tree."""
    parent = list(range(n))

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    tree, extra = [], []
    adj = {i: [] for i in range(n)}
    for k, (u, v) in enumerate(edges):
        ru, rv = find(u), find(v)
        if ru != rv:
            parent[ru] = rv
            tree.append(k)
            adj[u].append((v, k))
            adj[v].append((u, k))
        else:
            extra.append(k)

    def path(a, b):
        seen, st = {a: []}, [a]
        while st:
            z = st.pop()
            if z == b:
                return seen[z]
            for (w, k) in adj[z]:
                if w not in seen:
                    seen[w] = seen[z] + [k]
                    st.append(w)
        return []

    return [set(path(edges[k][0], edges[k][1]) + [k]) for k in extra]


def factorises(delta, n, edges):
    """Is delta of the form z_i z_j ? (Harary: product +1 on every cycle)"""
    for cyc in cycle_basis(n, edges):
        p = 1
        for k in cyc:
            p *= delta[k]
        if p != 1:
            return False
    return True


def gauge_count(n):
    return 2 ** (n - 1)


# ============================================================
# Test structures
# ============================================================

def K(n):
    return n, [(i, j) for i in range(n) for j in range(i + 1, n)]


def cycle(n):
    return n, [(i, (i + 1) % n) for i in range(n)]


def torus(a, b):
    idx = lambda i, j: (i % a) * b + (j % b)
    e = set()
    for i in range(a):
        for j in range(b):
            e.add(tuple(sorted((idx(i, j), idx(i, j + 1)))))
            e.add(tuple(sorted((idx(i, j), idx(i + 1, j)))))
    return a * b, sorted(e)


def annulus(L, h=2):
    idx = lambda i, j: j * L + i
    e = set()
    for j in range(h):
        for i in range(L):
            e.add(tuple(sorted((idx(i, j), idx((i + 1) % L, j)))))
            if j + 1 < h:
                e.add(tuple(sorted((idx(i, j), idx(i, j + 1)))))
    return L * h, sorted(e)


STRUCTURES = [
    ("K_4  (complete)", K(4)),
    ("K_5  (complete)", K(5)),
    ("K_6  (complete)", K(6)),
    ("C_5  (sparse)", cycle(5)),
    ("C_6  (sparse)", cycle(6)),
    ("C_3xC_3 torus", torus(3, 3)),
    ("annulus L=4", annulus(4, 2)),
    ("annulus L=5", annulus(5, 2)),
    ("annulus L=6", annulus(6, 2)),
]


# ============================================================
# Q1 / Q2 -- which layer does C2 constrain, and is delta a gauge?
# ============================================================
print("Q1/Q2 -- Reading A: C2 constrains the PROPER signs y")
print("-" * 74)
print("  If every triangle of y is coherent and every triangle of sigma")
print("  is automatically coherent, then every triangle of delta is too.")
print("  On a complete graph triangles generate the cycle space, so delta")
print("  should factorise -- a pure gauge, carrying nothing.")
print()
print(f"  {'structure':>16s} {'n':>3s} {'m':>4s} {'c':>3s} {'#tri':>5s} "
      f"{'admissible delta':>17s} {'gauges 2^(n-1)':>15s} {'all gauge?':>11s}")

for label, (n, edges) in STRUCTURES:
    m = len(edges)
    if m > 15:
        print(f"  {label:>16s} {n:3d} {m:4d} {m-n+1:3d} {'--':>5s} "
              f"{'(not enumerated)':>17s} {gauge_count(n):15d} {'--':>11s}")
        continue
    em = eidx_map(edges)
    tris = triangles_of(n, edges)
    c = m - n + 1
    adm = set()
    for y in itertools.product((1, -1), repeat=m):
        if not all(tri_ok(y, T, em) for T in tris):
            continue
        # sigma is any induced configuration; delta = y * sigma
        for xbits in range(1 << n):
            x = [1 if (xbits >> i) & 1 else -1 for i in range(n)]
            sig = induced(x, edges)
            adm.add(tuple(y[k] * sig[k] for k in range(m)))
    allg = all(factorises(d, n, edges) for d in adm)
    print(f"  {label:>16s} {n:3d} {m:4d} {c:3d} {len(tris):5d} "
          f"{len(adm):17d} {gauge_count(n):15d} {str(allg):>11s}")
print()

print("Q1/Q2 -- Reading B: C2 constrains only the INDUCED signs sigma")
print("-" * 74)
print("  Then y is unconstrained, delta ranges over all 2^m sign patterns,")
print("  and the non-gauge part has dimension c = m - n + 1: the number of")
print("  independent cycles. delta then carries genuine information --")
print("  exactly c bits of it -- and is NOT removable by relabelling.")
print()
print(f"  {'structure':>16s} {'n':>3s} {'m':>4s} {'c':>3s} "
      f"{'all delta 2^m':>14s} {'gauges 2^(n-1)':>15s} "
      f"{'non-gauge 2^c':>14s} {'check':>7s}")
for label, (n, edges) in STRUCTURES:
    m = len(edges)
    if m > 18:
        continue
    c = m - n + 1
    gau = sum(1 for d in itertools.product((1, -1), repeat=m)
              if factorises(d, n, edges))
    ok = (gau == gauge_count(n)) and (2 ** m == gauge_count(n) * 2 ** c)
    print(f"  {label:>16s} {n:3d} {m:4d} {c:3d} {2**m:14d} {gau:15d} "
          f"{2**c:14d} {str(ok):>7s}")
print()
print("  The factorisation 2^m = 2^(n-1) * 2^c is the cyclomatic identity")
print("  again: n-1 gauge dimensions, c observable ones. Under reading B")
print("  the relation layer carries c independent bits that no relabelling")
print("  of entities can remove. On a COMPLETE graph c is large but every")
print("  cycle is triangle-generated, so C2 on y would kill them all --")
print("  which is precisely reading A. The two readings differ exactly by")
print("  whether C2 sees the relation layer.")
print()


# ============================================================
# Q3 -- the beat: two desynchronised pulsations
# ============================================================
print("Q3 -- Two layers pulsing with different phase bipartitions")
print("-" * 74)
print("  Entity layer pulses by switching a vertex subset S (D68 Thm 6.3).")
print("  Relation layer pulses by its own involution: flip the y of every")
print("  edge in a fixed edge subset F. Both are involutions, so each")
print("  alone has period 2. The question is what delta does.")
print()


def beat(n, edges, S, F, steps=8):
    m = len(edges)
    x = [1] * n
    y = [1] * m
    out = []
    for t in range(steps):
        sig = induced(x, edges)
        out.append(tuple(y[k] * sig[k] for k in range(m)))
        x = [(-x[i] if i in S else x[i]) for i in range(n)]
        y = [(-y[k] if k in F else y[k]) for k in range(m)]
    return out


def exact_period(seq):
    L = len(seq)
    for T in range(1, L // 2 + 1):
        if all(seq[t] == seq[t + T] for t in range(L - T)):
            return T
    return None


for label, (n, edges) in STRUCTURES[:6]:
    m = len(edges)
    if m > 15 or n > 6:
        print(f"  {label:>16s}: skipped (too large for exhaustive beat)")
        continue
    em = eidx_map(edges)
    periods = {}
    nonfixed = 0
    total = 0
    for Sb in range(1 << n):
        S = {i for i in range(n) if (Sb >> i) & 1}
        for Fb in range(min(1 << m, 256)):
            F = {k for k in range(m) if (Fb >> k) & 1}
            seq = beat(n, edges, S, F)
            T = exact_period(seq)
            total += 1
            periods[T] = periods.get(T, 0) + 1
            if len(set(seq)) > 1:
                nonfixed += 1
    print(f"  {label:>16s}: {total} (S,F) pairs sampled; "
          f"non-constant delta in {nonfixed} "
          f"({100.0*nonfixed/total:.1f}%)")
    print(f"  {'':>16s}  period spectrum: " +
          ", ".join(f"{k}:{v}" for k, v in sorted(periods.items(),
                                                  key=lambda z: (z[0] is None, z[0]))))
print()
print("  A delta that is non-constant for most (S,F) pairs means the two")
print("  layers genuinely beat against each other. But note carefully: a")
print("  PERIOD-2 beat is still a closed cycle, not a motor. What would")
print("  matter is a period LONGER than 2, since C1 admits only 2-cycles")
print("  on a single layer -- a longer period could only come from the")
print("  two layers together.")
print()


# ============================================================
# Q3b -- are there periods longer than 2?
# ============================================================
print("Q3b -- Periods longer than 2: the only place a motor could hide")
print("-" * 74)
for label, (n, edges) in STRUCTURES[:6]:
    m = len(edges)
    if m > 15 or n > 6:
        print(f"  {label:>16s}: skipped")
        continue
    long_p = {}
    for Sb in range(1 << n):
        S = {i for i in range(n) if (Sb >> i) & 1}
        for Fb in range(min(1 << m, 256)):
            F = {k for k in range(m) if (Fb >> k) & 1}
            T = exact_period(beat(n, edges, S, F))
            if T is not None and T > 2:
                long_p[T] = long_p.get(T, 0) + 1
    print(f"  {label:>16s}: periods > 2 -> "
          f"{long_p if long_p else 'NONE'}")
print()
print("  If no period exceeds 2 anywhere, the two-layer construction adds")
print("  no dynamics: both involutions commute and the pair is still an")
print("  involution. That would be a clean negative result and would close")
print("  the beat idea, leaving the two-layer picture as a description")
print("  rather than a mechanism.")
print()

print("=" * 74)
print("HOW TO READ THIS SCRIPT")
print("=" * 74)
print("  Q1/Q2 reading A: if 'all gauge?' is True everywhere, then under")
print("        the reading that C2 constrains the relation layer, the")
print("        disagreement is removable by relabelling and carries")
print("        nothing. The two-layer picture collapses.")
print("  Q1/Q2 reading B: the non-gauge part has dimension c. On sparse")
print("        meshes c is large, so the relation layer would carry real")
print("        information -- but only if C2 does NOT constrain it.")
print("        Which reading is correct is a question about the axioms,")
print("        not about this computation, and is NOT settled here.")
print("  Q3/Q3b: whether two desynchronised involutions produce anything")
print("        of period greater than 2. If not, no motor.")
print("=" * 74)
